blank_issues_enabled: true
contact_links:
  - name: Course site
    # url: https://<your-username>.github.io/git-oss-course/
    url: https://proimodi.github.io/git-oss-course/
    about: Lesson content, quizzes, and assignment instructions for this org.
